title: Mallikarjunaiah Muddamallappa
url: "https://jaiminbrahmbhatt.github.io/testport/"
baseurl: ""

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

tracking_id: UA-156013933-1

sass:
    style: compressed
    sass_dir: _sass
theme: jekyll-theme-cayman